#!/usr/bin/python3

import requests
import lzma

SOURCES = 'http://ftp.us.debian.org/debian/dists/sid/main/' \
          'source/Sources.xz'
PACKAGES = 'http://ftp.us.debian.org/debian/dists/sid/main/' \
          'binary-amd64/Packages.xz'


def makeDigest(txt):
    """Parse a Packages/Sources file to a 2-level dict, keyed on package"""

    def dmap(txt):
        return dict([x.split(': ', 1) for x in txt.split('\n') if ': ' in x])

    digest = [dmap(x) for x in txt.split('\n\n') if 'Package' in x]

    result = {}
    for dig in digest:
        dig['Package'] = dig['Package'].split(' ')[0]
        result[dig['Package']] = dig

    return result


def getDigest(url):
    r = requests.get(url)

    compressed = r.content

    txt = lzma.LZMADecompressor().decompress(compressed).decode()

    return makeDigest(txt)


def parseDeps(txt):
    """Parse a Depends line to a naive set of dependencies"""

    rawlist = {x.split(' ')[0] for x in txt.split(', ') if x}
    parsedlist = {x.split(':')[0] for x in rawlist}

    return parsedlist


def expandDeps(depset, pdig):
    """Expand a set of dependencies recursively"""

    new = set(depset)
    result = set(depset)

    while new:
        result |= new
        temp = set()
        for dep in new:
            try:
                temp = temp.union(pdig[dep]['deplist'])
            except KeyError:
                pass
        new = temp - result

    return result


def fleshOutDigest(sdig, pdig):
    for src in sorted(sdig):
        sdig[src]['binaries'] = set()

        sdig[src]['deplist'] = set()
        for deptype in [
                'Build-Depends',
                'Build-Depends-Indep',
                'Build-Depends-Arch'
                ]:
            if deptype in sdig[src]:
                sdig[src]['deplist'] |= parseDeps(sdig[src][deptype])

    for pkg in sorted(pdig):
        if 'Source' not in pdig[pkg]:
            pdig[pkg]['Source'] = pkg
        else:
            pdig[pkg]['Source'] = pdig[pkg]['Source'].split(' ')[0]

        sdig[pdig[pkg]['Source']]['binaries'].add(pkg)

        pdig[pkg]['deplist'] = set()
        for deptype in ['Depends', 'Pre-Depends']:
            if deptype in pdig[pkg]:
                pdig[pkg]['deplist'] |= parseDeps(pdig[pkg][deptype])


def calcAlldeps(digest, pdig):
    for pkg in digest:
        digest[pkg]['alldeps'] = expandDeps(digest[pkg]['deplist'], pdig)


def main():
    sdig = getDigest(SOURCES)
    pdig = getDigest(PACKAGES)

    fleshOutDigest(sdig, pdig)

    pdig['golang-any']['deplist'] = set()

    calcAlldeps(sdig, pdig)
    calcAlldeps(pdig, pdig)

    # get golang source packages
    gosrc = {x for x in sdig if 'golang-any' in sdig[x]['alldeps']}
    gosrc |= {x for x in sdig if 'golang-go' in sdig[x]['alldeps']}

    # get affected source packages
    affected = {x for x in gosrc if 'golang-go' in sdig[x]['alldeps']}

    # get affected binary packages
    for src in sorted(affected):
        binaries = {x for x in sdig[src]['binaries'] if pdig[x]['Architecture'] != 'all'}
        causes = {x for x in sdig[src]['alldeps'] if x in pdig and 'golang-go' in pdig[x]['deplist']}

        if binaries:
            print()
            print("%s: %s" % (src, ', '.join(sorted(binaries))))
            for cause in sorted(causes):
                print("    ", cause)


if __name__ == '__main__':
    main()
